[package]
name = "crecover"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
platform-dirs = "0.3.0"
winapi = { version = "0.3", features = ["dpapi", "wincrypt", "winnt", "minwindef"] }
base64 = "0.13.0"
aes-gcm = "0.9.4"
reqwest = { version = "0.11.3", features = ["blocking", "json","multipart"] }


[dependencies.rusqlite]
version = "0.25.3"
features = ["bundled"]
